# Generated by Django 4.1.2 on 2023-02-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signupcourses',
            unique_together={('email', 'course')},
        ),
    ]
